pipeline {
    agent any

    // Parameters for manual build
    parameters {
        booleanParam(
	        name: 'DEPLOY',
	        defaultValue: true,
	        description: 'Deploy locally after build?'
	    )
        string(
	        name: 'GIT_BRANCH',
	        defaultValue: 'main',
	        description: 'Git branch to fetch latest code from'
	    )
	    string(
	        name: 'PORT',
	        defaultValue: '8091',
	        description: 'Port on which application shall run'
	    )
    }

    environment {
	    // auto-detect service folder name
        SERVICE_NAME = "${env.WORKSPACE.split('/').last()}"
    }

    stages {
        stage('Checkout Latest Code') {
            steps {
                echo "Fetching latest code from branch ${params.GIT_BRANCH}..."
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "refs/heads/${params.GIT_BRANCH}"]],
                    userRemoteConfigs: [[
                        url: 'git@github.com:shashipanta/easy-rento-ms.git',
                        credentialsId: 'github-ssh'
                    ]]
                ])
            }
        }

        stage('Debug workspace') {
            steps {
                sh 'ls -la'
            }
        }

        stage('Build JAR') {
            steps {
                sh "./${env.SERVICE_NAME}/./mvnw clean package -DskipTests"
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image for ${env.SERVICE_NAME}..."
                sh "docker build -t ${env.SERVICE_NAME}:latest ."
            }
        }

        stage('Deploy Locally (Optional)') {
            when { expression { params.DEPLOY == true } }
            steps {
                script {
                    // Read .env file
                    def envVars = [:]
                    if (fileExists('.env')) {
                        envVars = readFile('.env').split('\n')
                            .findAll { it.contains('=') }
                            .collect { it.split('=') }
                            .collectEntries { [(it[0]): it[1]] }
                    }

                    def port = envVars['PORT'] ?: ${params.PORT}

                    sh """
                        docker stop ${env.SERVICE_NAME} || true
                        docker rm ${env.SERVICE_NAME} || true
                        docker run -d --name ${env.SERVICE_NAME} -p ${port}:${port} --env-file .env ${env.SERVICE_NAME}:latest
                    """
                }
            }
        }
    }

    post {
        success { echo "✅ ${env.SERVICE_NAME} Docker image built and deployed!" }
        failure { echo "❌ ${env.SERVICE_NAME} build/deploy failed!" }
    }
}